# Site settings
title: 徐明的博客
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  拥抱新生命，奔向未来！
baseurl: "https://yu826717.github.io/xgi" # the subpath of your site, 
url: "https://yu826717.github.io/xgi" # the base hostname & protocol for your site
twitter_username: chyni 
github_username:  xuming

# Build settings
markdown: kramdown
